### ISSUE TITLE
Narnardinath may be too farmable

### ISSUE THREAD

**Issue by Logg-y** [The-Frozen-North/tfn-module#832]
This is a lot of loot locked behind just one enemy kill, that can be farmed repeatedly without having a dungeon to work through.

I am not sure that this is great, but with the area as is there is no dungeon to kick people out of.

**Comment by b5635** [comment]
Agreed, I should add a dungeon for this. My initial thought is that it's _so_ far out of the way it sorta counts but not really they can just sit there and farm it.

**Comment by b5635** [comment]
Just added a small dungeon that should be supposedly CR 12, not sure if it is. There's a lot of elementals / mephits in a small space, and you fight off against a greater air / water elemental at the end
