### ISSUE TITLE
"Peeking" on area refresh pushes back the refresh too far

### ISSUE THREAD

**Issue by Logg-y** [The-Frozen-North/tfn-module#833]
It may be better to have the refresh progress count backwards (possibly at increased speed) to the 2/3 mark instead of instantly setting it back, so that you can peek in on areas to see if they are refreshed without delaying them by very much.

This would mean that leaving an area you spent ages clearing to go somewhere else for 2 minutes still can't surprise you with a refresh.

**Comment by b5635** [comment]
I thinking counting backwards is a good fix
