### ISSUE TITLE
Maker clay golems shouldn't have full immuntiy to non crush

### ISSUE THREAD

**Issue by Logg-y** [The-Frozen-North/tfn-module#835]

**Comment by b5635** [comment]
It does seem iconic for those immunities, I agree that unless you had knowledge it's kind of an unwinnable situation. i.e. a player would have to know to bring a +1 crushing weapon.

Would it be OP if it was changed to 75% slash / pierce immune? Not impossible to beat but hard.

FWIW, the monster page for it. https://www.dandwiki.com/wiki/3e_SRD:Golem,_Clay

They seem even more OP in tabletop where they are immune to most spells
